module.exports = {
  productionSourceMap: false,
  pwa: {
    manifestOptions: {
      icons: [
        {
          src: './img/icons/android-chrome-192x192.png',
          sizes: '192x192',
          type: 'image/png',
        },
        {
          src: './img/icons/android-chrome-512x512.png',
          sizes: '512x512',
          type: 'image/png',
        },
        {
          src: './img/icons/android-chrome-maskable-192x192.png',
          sizes: '192x192',
          type: 'image/png',
          purpose: 'maskable',
        },
        {
          src: './img/icons/android-chrome-maskable-512x512.png',
          sizes: '512x512',
          type: 'image/png',
          purpose: 'maskable',
        },
        {
          src: './img/icons/apple-touch-icon-60x60.png',
          sizes: '60x60',
          type: 'image/png',
        },
        {
          src: './img/icons/apple-touch-icon-76x76.png',
          sizes: '76x76',
          type: 'image/png',
        },
        {
          src: './img/icons/apple-touch-icon-120x120.png',
          sizes: '120x120',
          type: 'image/png',
        },
        {
          src: './img/icons/apple-touch-icon-152x152.png',
          sizes: '152x152',
          type: 'image/png',
        },
        {
          src: './img/icons/apple-touch-icon-180x180.png',
          sizes: '180x180',
          type: 'image/png',
        },
        {
          src: './img/icons/apple-touch-icon.png',
          sizes: '180x180',
          type: 'image/png',
        },
        {
          src: './img/icons/favicon-16x16.png',
          sizes: '16x16',
          type: 'image/png',
        },
        {
          src: './img/icons/favicon-32x32.png',
          sizes: '32x32',
          type: 'image/png',
        },
        {
          src: './img/icons/msapplication-icon-144x144.png',
          sizes: '144x144',
          type: 'image/png',
        },
        {
          src: './img/icons/mstile-150x150.png',
          sizes: '150x150',
          type: 'image/png',
        },
      ],
    },
    themeColor: "#1a1a1a",
    workboxPluginMode: 'InjectManifest',
    workboxOptions: {
      exclude: [
        /\.map$/,
      ],
      // solution for the current version of workbox plugin
      // https://forum.vuejs.org/t/vue-cli-plugin-pwa-additionalmanifestentries-error/89234/5
      manifestTransforms: [
        (originalManifest) => {
          const manifest = originalManifest.concat([
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/addon/mode/overlay.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/codemirror.min.css' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/codemirror.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/apl/apl.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/asciiarmor/asciiarmor.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/asn.1/asn.1.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/asterisk/asterisk.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/brainfuck/brainfuck.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/clike/clike.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/clojure/clojure.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/cmake/cmake.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/cobol/cobol.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/coffeescript/coffeescript.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/commonlisp/commonlisp.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/crystal/crystal.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/css/css.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/cypher/cypher.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/d/d.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/dart/dart.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/diff/diff.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/django/django.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/dockerfile/dockerfile.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/dtd/dtd.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/dylan/dylan.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/ebnf/ebnf.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/ecl/ecl.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/eiffel/eiffel.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/elm/elm.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/erlang/erlang.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/factor/factor.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/fcl/fcl.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/forth/forth.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/fortran/fortran.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/gas/gas.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/gfm/gfm.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/gherkin/gherkin.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/go/go.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/groovy/groovy.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/haml/haml.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/haskell-literate/haskell-literate.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/haskell/haskell.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/haxe/haxe.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/haxe/haxe.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/htmlembedded/htmlembedded.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/htmlmixed/htmlmixed.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/http/http.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/idl/idl.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/javascript/javascript.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/jinja2/jinja2.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/jsx/jsx.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/jsx/jsx.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/julia/julia.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/livescript/livescript.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/lua/lua.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/markdown/markdown.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/mathematica/mathematica.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/mbox/mbox.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/meta.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/mirc/mirc.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/mllike/mllike.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/modelica/modelica.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/mscgen/mscgen.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/mumps/mumps.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/nginx/nginx.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/nsis/nsis.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/ntriples/ntriples.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/octave/octave.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/oz/oz.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/pascal/pascal.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/pegjs/pegjs.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/perl/perl.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/php/php.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/pig/pig.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/powershell/powershell.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/properties/properties.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/protobuf/protobuf.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/pug/pug.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/puppet/puppet.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/python/python.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/q/q.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/r/r.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/rpm/rpm.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/rst/rst.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/ruby/ruby.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/rust/rust.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/sas/sas.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/sass/sass.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/scheme/scheme.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/shell/shell.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/sieve/sieve.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/slim/slim.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/smalltalk/smalltalk.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/smarty/smarty.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/solr/solr.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/soy/soy.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/sparql/sparql.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/spreadsheet/spreadsheet.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/sql/sql.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/stex/stex.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/stylus/stylus.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/swift/swift.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/tcl/tcl.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/textile/textile.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/tiddlywiki/tiddlywiki.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/tiki/tiki.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/toml/toml.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/tornado/tornado.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/troff/troff.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/ttcn-cfg/ttcn-cfg.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/ttcn/ttcn.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/turtle/turtle.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/twig/twig.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/vb/vb.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/vbscript/vbscript.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/velocity/velocity.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/verilog/verilog.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/verilog/verilog.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/vhdl/vhdl.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/vue/vue.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/webidl/webidl.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/xml/xml.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/xquery/xquery.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/yacas/yacas.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/yaml/yaml.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/z80/z80.min.js' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/theme/yeti.min.css' },
            { url: 'https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.26.0/moment.min.js' },
            { url: 'https://code.cdn.mozilla.net/fonts/fira.css', revision: 'v1' },
            { url: 'https://code.cdn.mozilla.net/fonts/ttf/FiraMono-Bold.ttf', revision: 'v1' },
            { url: 'https://code.cdn.mozilla.net/fonts/ttf/FiraMono-Regular.ttf', revision: 'v1' },
            { url: 'https://code.cdn.mozilla.net/fonts/ttf/FiraSans-Regular.ttf', revision: 'v1' },
            { url: 'https://code.cdn.mozilla.net/fonts/ttf/FiraSans-Medium.ttf', revision: 'v1' },
            { url: 'https://code.cdn.mozilla.net/fonts/woff/FiraMono-Bold.woff', revision: 'v1' },
            { url: 'https://code.cdn.mozilla.net/fonts/woff/FiraMono-Regular.woff', revision: 'v1' },
            { url: 'https://code.cdn.mozilla.net/fonts/woff/FiraSans-Regular.woff', revision: 'v1' },
            { url: 'https://code.cdn.mozilla.net/fonts/woff/FiraSans-Medium.woff', revision: 'v1' },
            // lato is currently required by bootstrap
            // todo: determine if this can be excluded
            { url: 'https://fonts.googleapis.com/css?family=Lato:400,700,400italic&display=swap', revision: 'v1' },
            { url: 'https://stackpath.bootstrapcdn.com/bootswatch/4.5.0/darkly/bootstrap.min.css' },
          ]);
          // optionally set warning messages
          const warnings = [];
          return { manifest, warnings };
        },
      ],
      swSrc: 'src/service-worker.js',
    },
  },
};
