export const ACTIVATE_CONTEXT = 'ACTIVATE_CONTEXT';
export const ADD_DOCUMENT = 'ADD_DOCUMENT';
export const BLUR_EDITOR = 'BLUR_EDITOR';
export const CLEAR_EDITOR = 'CLEAR_EDITOR';
export const CREATE_DOCUMENT = 'CREATE_DOCUMENT';
export const DEACTIVATE_CONTEXT = 'DEACTIVATE_CONTEXT';
export const DISCARD_DOCUMENT = 'DISCARD_DOCUMENT';
export const EDIT_DOCUMENT = 'EDIT_DOCUMENT';
export const FOCUS_EDITOR = 'FOCUS_EDITOR';
export const HIDE_MENU = 'HIDE_MENU';
export const LOAD_DOCUMENT = 'LOAD_DOCUMENT';
export const LOAD_DOCUMENTS = 'LOAD_DOCUMENTS';
export const LOADED = 'LOADED';
export const RESTORE_DOCUMENT = 'RESTORE_DOCUMENT';
export const SET_CONTEXT_TAGS = 'SET_CONTEXT_TAGS';
export const SET_EDITOR = 'SET_EDITOR';
export const SET_EDITOR_CONTEXT = 'SET_EDITOR_CONTEXT';
export const SET_EDITOR_DOCUMENT = 'SET_EDITOR_DOCUMENT';
export const SET_OFFLINE = 'SET_OFFLINE';
export const SET_ONLINE = 'SET_ONLINE';
export const SHOW_MENU = 'SHOW_MENU';

export default {
  ACTIVATE_CONTEXT,
  ADD_DOCUMENT,
  BLUR_EDITOR,
  CLEAR_EDITOR,
  CREATE_DOCUMENT,
  DEACTIVATE_CONTEXT,
  DISCARD_DOCUMENT,
  EDIT_DOCUMENT,
  FOCUS_EDITOR,
  HIDE_MENU,
  LOAD_DOCUMENT,
  LOAD_DOCUMENTS,
  LOADED,
  RESTORE_DOCUMENT,
  SET_CONTEXT_TAGS,
  SET_EDITOR,
  SET_EDITOR_CONTEXT,
  SET_EDITOR_DOCUMENT,
  SET_OFFLINE,
  SET_ONLINE,
  SHOW_MENU,
};
