export const ACTIVATE_CONTEXT = 'ACTIVATE_CONTEXT';
export const ADD_DOCUMENT = 'ADD_DOCUMENT';
export const BLUR_EDITOR = 'BLUR_EDITOR';
export const DEACTIVATE_CONTEXT = 'DEACTIVATE_CONTEXT';
export const DISCARD_DOCUMENT = 'DISCARD_DOCUMENT';
export const DUPLICATE_DOCUMENT = 'DUPLICATE_DOCUMENT';
export const DOCUMENTS_LOADED = 'DOCUMENTS_LOADED';
export const EDIT_DOCUMENT = 'EDIT_DOCUMENT';
export const FOCUS_EDITOR = 'FOCUS_EDITOR';
export const HIDE_MENU = 'HIDE_MENU';
export const LOAD_DOCUMENT = 'LOAD_DOCUMENT';
export const LOAD_DOCUMENTS = 'LOAD_DOCUMENTS';
export const MERGE_DOCUMENTS = 'MERGE_DOCUMENTS';
export const RESTORE_DOCUMENT = 'RESTORE_DOCUMENT';
export const SET_CONTEXT_TAGS = 'SET_CONTEXT_TAGS';
export const SET_DOCUMENT = 'SET_DOCUMENT';
export const SET_EDITOR = 'SET_EDITOR';
export const SET_MOD_KEY = 'SET_MOD_KEY';
export const SET_OFFLINE = 'SET_OFFLINE';
export const SET_ONLINE = 'SET_ONLINE';
export const SET_RIGHT_SIDEBAR_VISIBILITY = 'SET_RIGHT_SIDEBAR_VISIBILITY';
export const SHOW_MENU = 'SHOW_MENU';
export const TOUCH_DOCUMENT = 'TOUCH_DOCUMENT';

export default {
  ACTIVATE_CONTEXT,
  ADD_DOCUMENT,
  BLUR_EDITOR,
  DEACTIVATE_CONTEXT,
  DISCARD_DOCUMENT,
  DUPLICATE_DOCUMENT,
  DOCUMENTS_LOADED,
  EDIT_DOCUMENT,
  FOCUS_EDITOR,
  HIDE_MENU,
  LOAD_DOCUMENT,
  LOAD_DOCUMENTS,
  MERGE_DOCUMENTS,
  RESTORE_DOCUMENT,
  SET_CONTEXT_TAGS,
  SET_DOCUMENT,
  SET_EDITOR,
  SET_MOD_KEY,
  SET_OFFLINE,
  SET_ONLINE,
  SET_RIGHT_SIDEBAR_VISIBILITY,
  SHOW_MENU,
  TOUCH_DOCUMENT,
};
